Remove obsolete JVM arg from gradle.properties
The `MaxPermSize` is obsolete and once we upgrade to JDK 17 and beyond,
having this in gradle.properties will prevent Gradle from starting due
to:

```
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```