Improve build error on dirty git build dependencies
Improve this unhelpful error message:

```
Could not create task ':generateJsonTestSuite'.
> Could not create task of type 'GenerateJsonTestSuiteTask'.
   > ERROR: Dirty git status in /Aboslute/path/to/kson/buildSrc/support/jsonsuite.  Please ensure the git status is clean or delete the directory and re-run this script
```

This error message wasn't doing a good enough job of explaining what the
problem is and why it needs to be fixed.  Even worse, it would also blow
up on OS files `.DS_Store` and `Thumbs.db` that can quietly sneak in.
This naturally caused some real confusion for some developers. So,
to improve all this, we:
- edit the error message to be more clear and include a listing of dirty
  files in its output
- allow the build to proceed if the only "dirtyness" in the git repo is
  harmless untracked `.DS_Store` or `Thumbs.db` files

Here's the new error message format:

```
Could not create task ':generateJsonTestSuite'.
> Could not create task of type 'GenerateJsonTestSuiteTask'.
   > ERROR: Dirty git status in `/Absolute/path/to/kson/buildSrc/support/jsonsuite/JSONTestSuite`.
     This needs to be clean since we generate files from this repo.
     Suggested fixes:
     - either clean up the git status in `/Absolute/path/to/kson/buildSrc/support/jsonsuite/JSONTestSuite`
     - or, delete `/Absolute/path/to/kson/buildSrc/support/jsonsuite/JSONTestSuite`
       so it is re-cloned on the next build

     # Dirty Git Status in `/Absolute/path/to/kson/buildSrc/support/jsonsuite/JSONTestSuite`:
     Added files: [dirty_added.txt]
     Untracked files: [dirty_untracked.txt]
     Modified files (not staged): [test_parsing/i_number_huge_exp.json]
```